\documentclass[11pt, A4]{article}
\usepackage[brazil]{babel}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}
%\usepackage{natbib}
\usepackage{fancyhdr,multicol}
\setlength{\hoffset}{-0.5in}
\setlength{\textwidth}{6in}
\setlength{\voffset}{-0.1in}
%\setlength{\textheight}{10in}
\setlength{\parindent}{0pt}
\pdfpagewidth=\paperwidth
\pdfpageheight=\paperheight
\newcommand{\R}{{\sf R}}
\newcommand{\code}[1]{\texttt{#1}}
\renewcommand{\footrulewidth}{0.5pt} %faz a regua do rodapé aparecer
% Mudancas de layout do codigo (nao funfam)
% \DefineVerbatimEnvironment{Sinput}{Verbatim} {xleftmargin=2em}
% \DefineVerbatimEnvironment{Soutput}{Verbatim}{xleftmargin=2em}
% \DefineVerbatimEnvironment{Scode}{Verbatim}{xleftmargin=2em}
% \fvset{listparameters={\setlength{\topsep}{0pt}}}
% \renewenvironment{Schunk}{\vspace{\topsep}}{\vspace{\topsep}}
\SweaveOpts{eval=T, keep.source=T}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
%\maketitle
\pagestyle{fancyplain}
\lhead[] {\textsl{II LETiro intelectual -- 2012}\\%
	\textsl{Teste do pacote \code{sads}}}
\rhead[\fancyplain{}{\textsl{\thepage}}]%
      {\fancyplain{}{\textsl{\thepage}}}
\rfoot[]{\textsl{Laboratório de Ecologia Teórica - LAGE - IB - USP}}
\lfoot[]{}
\cfoot[]{}
\thispagestyle{empty}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%\vspace{-10in}
\begin{center}
	{\normalsize Laboratório de Ecologia Téorica - LAGE - IB - USP}	\\\vspace{2\baselineskip}
	\textbf{\Large Tutorial para teste de aplicativo}	\\\vspace{0.5\baselineskip}
	\textbf{\Large Pacote \code{sads} v.0.3}		\\\vspace{0.5\baselineskip}
	{\normalsize Paulo Inácio Prado e Murilo Dantas Miranda}        \\\vspace{2\baselineskip}
\end{center}

@ 
<<R setup, echo=FALSE, >>=
options(width=60, continue=" ")
@ %def 

\section{Instalação}

O pacote ainda está em testes, por isso não está disponível no repositório CRAN do \R. No momento versão de teste compilada para Linux e para Ruindows. Para este tutorial você precisrá também do pacote de dados \code{Hughes}, disponível para as mesmas plataformas. 
Para instalar a versão de teste do pacote \code{sads}, você precisa adicionar os seguintes pacotes à sua instalação de \R:
\begin{itemize}
\item \code{bbmle} \cite{bolker2012}
\item \code{poilog} \cite{grotan2008}
\item \code{VGAM} \cite{yee2012}
\end{itemize}

\subsection{Instalação em Linux}
\label{sec:instalacao-em-linux}
Copie os arquivos \code{sads\_0.2.06.tar.gz} e \code{Hughes\_1.0.tar.gz} para um diretório, carregue os pacotes no \R \ e chame-os com
@ 
<<installation, eval=FALSE>>=
install.packages("diretorio/sads_0.2.06.tar.gz", repos=NULL)
install.packages("diretorio/Hughes_1.0.tar.gz", repos=NULL)
library(sads)
library(Hughes)
@ %def 

onde \code{diretorio} é o caminho para o diretório onde você copiou o arquivo.

\subsection{Instalação em Ruindows}
\label{sec:instalacao-em-linux}
Copie os arquivos \code{sads\_0.2.06.zip} e \code{Hughes\_1.0.zip} para um diretório, carregue os pacotes no \R \ e chame-os com
@ 
<<installation, eval=FALSE>>=
install.packages("diretorio/sads_0.2.06.zip", repos=NULL)
install.packages("diretorio/Hughes_1.0.zip", repos=NULL)
library(sads)
library(Hughes)
@ %def 

onde \code{diretorio} é o caminho para o diretório onde você copiou o arquivo.


\section{Análise exploratória}
\label{sec:analise-exploratoria}

\subsection{Tabela e gáfico de oitavas}
\label{sec:oitavas}

@ 
<<Tabulating species in octaves>>=
data(moths)# William's moth data
(moths.oc <- octav(moths))
@ %def 

\begin{figure}
\begin{center}
@ 
<<Ploting octaves, fig=TRUE>>=
par(mfrow=c(2,1))
plot(moths.oc)
##Changing graphical parameters
plot(moths.oc, col="white", ylab="N de espécies", 
     xlab="Oitavas de abundância")
par(mfrow=c(1,1))
@ %def 
\end{center}  
\caption{bla}
\label{fig:um}
\end{figure}

@ 
<<Octaves for biomass>>=
(arn.oc <- octav(ARN82.eB.apr77))
plot(arn.oc)
@ %def 

\subsection{Tabelas e gráfico de rank-abundância}
\label{sec:rank_abund}


@ 
<<Rank-abundance table and plots>>=
head(moths.rad <- rad(moths))
plot(moths.rad)
head(arn.rad <- rad(ARN82.eB.apr77))
plot(arn.rad)
@ %def 

\section{Ajuste de modelos}
\label{sec:ajuste-e-selecao}

\subsection{Ajuste: objeto \code{fitsad}}
\label{sec:ajust-objeto-fitsad}
@ 
<<Fitting a logseries model>>=
(moths.ls <- fitsad(moths,"ls"))
@ %def 

@ 
<<Operations on fitsad object>>=
summary(moths.ls)
coef(moths.ls)
logLik(moths.ls)
AIC(moths.ls)
@ %def 


\subsection{Avaliação do ajuste}
\label{sec:avaliacao-do-ajuste}

@ 
<<Profiling and intervals>>=
moths.ls.prf <- profile(moths.ls)
plotprofmle(moths.ls.prf)# log-likelihood profile
plot(moths.ls.prf)# z-transformed profile
confint(moths.ls.prf) # conf intervals
@ %def 

@ 
<<Plot of predicted values, eval=FALSE>>=
par(mfrow=c(2,2))
plot(moths.ls)
par(mfrow=c(1,1))
@ %def 


\section{Comparação de modelos}
\label{sec:comp-de-model}

@ 
<<Fitting two other models>>=
(moths.pl <- fitsad(moths,"poilog"))#default is zero-truncated
(moths.ln <- fitsad(moths,"lnorm", trunc=0.5)) # lognormal truncated at 0.5
(moths.gm <- fitsad(moths,"gamma"))
@ %def 

@ 
<<Model selection table>>=
AICtab(moths.ls, moths.pl, moths.ln, moths.gm)
@ %def 

@ 
<<Graphical comparison: octaves>>=
head(moths.ls.oc <- octavpredt(moths.ls))# substituir por octavpred
head(moths.pl.oc <- octavpredt(moths.pl))
head(moths.ln.oc <- octavpredt(moths.ln))
plot(moths.oc)
lines(moths.ls.oc, col="blue")
lines(moths.pl.oc, col="red")
lines(moths.ln.oc, col="green")
legend("topright", c("Logseries", "Poisson-lognormal", "Truncated lognormal"), lty=1, 
       col=c("blue","red", "green"))
@ %def 


@ 
<<Graphical comparison: octaves>>=
head(moths.ls.rad <- radpredt(moths.ls)) # mudar para radpred
head(moths.pl.rad <- radpredt(moths.pl))## rank 1 com valor negativo
head(moths.ln.rad <- radpredt(moths.ln))
plot(moths.rad)
lines(moths.ls.rad, col="blue")
lines(moths.pl.rad, col="red")
lines(moths.ln.rad, col="green")
legend("topright", c("Logseries", "Poisson-lognormal", "Truncated lognormal"), lty=1, 
       col=c("blue","red", "green"))
@ %def 


\bibliographystyle{plain}
\bibliography{vignetes}
\end{document}
