library(sads)
#library(untb)
library(vegan)


data(BCI)
bci <- apply(BCI, 2, sum)

bci.gamma <- fitsad(bci, "gamma")
bci.geom <- fitsad(bci, "geom") #sem truncagem
bci.lnorm <- fitsad(bci, "lnorm")
bci.ls <- fitsad(bci, "ls")
bci.mand <- fitsad(bci, "mand") 
bci.nbinom <- fitsad(bci, "nbinom", start=c(0.457953, 0.004838)) #sem truncagem
bci.pareto <- fitsad(bci, "pareto")
bci.poilog <- fitsad(bci, "poilog")
bci.power <- fitsad(bci, "power")
bci.weibull <- fitsad(bci, "weibull")
bci.zipf <- fitsad(bci, "zipf")
bci.mzsm <- fitsad(bci, "mzsm", start=35)
bci.volkov <- fitsad(bci, "volkov", start=c(0.099, 49.99))

oc.bci.gamma <- octavpred(bci.gamma)
oc.bci.geom <- octavpred(bci.geom)
oc.bci.lnorm <- octavpred(bci.lnorm)
oc.bci.ls <- octavpred(bci.ls)
oc.bci.mand <- octavpred(bci.mand)
oc.bci.nbinom <- octavpred(bci.nbinom)
oc.bci.pareto <- octavpred(bci.pareto)
oc.bci.poilog <- octavpred(bci.poilog)
oc.bci.power <- octavpred(bci.power)
oc.bci.weibull <- octavpred(bci.weibull)
oc.bci.zipf <- octavpred(bci.zipf)
oc.bci.mzsm <- octavpred(bci.mzsm)
oc.bci.volkov <- octavpred(bci.volkov)

plot(octav(bci))
lines(oc.bci.gamma, col = 2)
lines(oc.bci.geom, col = 3)
lines(oc.bci.lnorm, col = 4)
lines(oc.bci.ls, col = 5)
lines(oc.bci.nbinom, col = 6)
lines(oc.bci.poilog, col = 7)
lines(oc.bci.pareto, col = 9)
lines(oc.bci.power, col = 2, lty = 2)
lines(oc.bci.weibull, col = 3, lty = 2)
lines(oc.bci.zipf, col = 4, lty = 2)
lines(oc.bci.mzsm, col = 5, lty = 2)
lines(oc.bci.mand, col = 6, lty = 2)
lines(oc.bci.volkov, col = 7, lty = 2)


rad.bci.gamma <- radpred(bci.gamma)
rad.bci.geom <- radpred(bci.geom)
rad.bci.lnorm <- radpred(bci.lnorm)
rad.bci.ls <- radpred(bci.ls)
rad.bci.mand <- radpred(bci.mand)
rad.bci.pareto <- radpred(bci.pareto)
rad.bci.nbinom <- radpred(bci.nbinom)
rad.bci.poilog <- radpred(bci.poilog)
rad.bci.power <- radpred(bci.power)
rad.bci.weibull <- radpred(bci.weibull)
rad.bci.zipf <- radpred(bci.zipf)
rad.bci.mzsm <- radpred(bci.mzsm)
rad.bci.volkov <- radpred(bci.volkov)

plot(rad(bci))
lines(rad.bci.gamma, col = 2)
lines(rad.bci.geom, col = 3)
lines(rad.bci.lnorm, col = 4)
lines(rad.bci.ls, col = 5)
lines(rad.bci.mand, col = 5)
lines(rad.bci.nbinom, col = 6)
lines(rad.bci.poilog, col = 7)
lines(rad.bci.pareto, col = 2)
lines(rad.bci.power, col = 2, lty = 2)
lines(rad.bci.weibull, col = 3, lty = 2)
lines(rad.bci.zipf, col = 4, lty = 2)
lines(rad.bci.mzsm, col = 5, lty = 2)
lines(rad.bci.volkov, col = 2, lty = 3)

par(mfrow=c(2,2))
plot(bci.gamma)
plot(bci.geom)
plot(bci.lnorm)
plot(bci.ls)
plot(bci.mand)
plot(bci.nbinom)
plot(bci.pareto)
plot(bci.poilog)
plot(bci.power)
plot(bci.pareto)
plot(bci.weibull)
plot(bci.zipf)
plot(bci.mzsm)
plot(bci.volkov)


ppsad(bci.ls)
qqsad(bci.ls)