\documentclass[11pt, A4]{article}
\usepackage[brazil]{babel}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}
\usepackage{Sweave}
%\usepackage{natbib}
\setlength{\parindent}{0pt}
\setlength{\hoffset}{-0.5in}
\setlength{\textwidth}{6in}
\setlength{\voffset}{-0.1in}
%\pdfpagewidth=\paperwidth
%\pdfpageheight=\paperheight
\newcommand{\R}{{\sf R}}
\newcommand{\code}[1]{\texttt{#1}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

%\setkeys{Gin}{width=0.9\textwidth}
\title{Package sads: ToDo list}
\author{Paulo Inácio Prado}
\maketitle

\section{Bugs and Issues}
\label{sec:bugs-issues}
\begin{itemize}
\item Check why
  @ 
<<eval=F>>=
pzipf(10,N=100,s=2) - sum(dzipf(1:10,N=100,s=2))
@ %def 
gives a small difference. Once solved include this command in help page. 
\item Check why \code{summary} for \code{fitsad} objects returned by \code{fitvolkov} results in a \code{summary} with a huge \code{call}. Probably due the use of \code{do.call} to call \code{mle2}.
\item Check warnings returned when detaching the package:
    @ 
<<eval=F>>=
detach("package:sads", unload=T)
@ %def 

\item Check incorrect calculations of \code{radpred} when data object is provided in argument \code{object}:
@
<<eval=F>>=
data(moths)
moths.ls <- fitsad(moths, "ls")
moths.rad.pred <- radpred(moths.ls)
moths.rad.pred2 <- radpred(object=moths, sad="ls", 
                             coef=list(alpha=35), distr="D")
moths.rad.pred3 <- radpred(object=moths, sad="ls", 
                             coef=list(alpha=35), distr="D", S=length(moths), N=sum(moths))
plot(moths.rad.pred)
lines(moths.rad.pred2, col="black")
lines(moths.rad.pred3, col="red")
@

\item Conferir funcao trueLL e seu uso na fitsad, pois pelo menos para dados de mariposas de Fisher
  resulta em melhoria do modelo lognormal truncado, mas o grafico de oitavas nao mostra isto
  @ 
<<TrueLL>>=
## TRUE likelihood 
##(Lindsey, J.K. 1999. Some stattistical heresies. _The Statistician 48(1): 1-40).
moths.ls <- fitsad(moths, "ls")
moths.pln <- fitsad(moths, "poilog")
moths.ln1 <- fitsad(moths, "lnorm", trunc=0.5)
moths.ln2 <- fitsad(moths, "lnorm", trunc=0.5, trueLL=F)
AICctab(moths.ls, moths.pln, moths.ln1, moths.ln2,
        nobs=length(moths), base=T, weights=T)
## Verificando: graficos parecem nao sustentar 
## o melhor desempenho do lognormal
plot(moths.oc)
lines(octavpred(moths.pln))
lines(octavpred(moths.ln1), col="red")
## E qqplots mostram melhor ajuste da Logserie

@ %def 

\end{itemize}

\subsection{Solved}
\label{sec:solved}
\begin{itemize}
\item Check why
  @ 
<<eval=F>>=
p.123 <-ppareto(1:3,shape=3,scale=1) 
sum(qpareto(p.123, 3, scale=1)-1:3)
@ %def 
gives a small difference. 
\paragraph{SOLVED:} difference because \code{ppareto(1,shape=3,scale=1)} is zero 
\end{itemize}

\section{Distributions}
\label{sec:distributions}
\item Distributions to include:
\begin{itemize}
  \begin{itemize}
  \item Continuous power
  \item Truncated power (or Power-bend)
  \item Geometric series
  \item Broken-stick (= Poisson sample of exponential?) 
  \end{itemize}
\item Allow Pareto distribution to return zero values when scale >= min(x). (Maybe not a good idea: may cause fitting problems.). 
\end{itemize}

\subsection{Done}
\label{sec:done}
\begin{itemize}
\item Make invalid parameters return \code{NaN}, instead than stoping. 
\end{itemize}

\section{Fitting}
\label{sec:fiting-functions}
\begin{itemize}
\item Evaluate if Mouillot \& Lepretre's \cite{mouillot2000} method for fitting Zipf-Mandelbrot is useful to find starting values for \code{fitmand};
\item Evaluate if Wilson's \cite{wilson2009} methods for fitting rads can/should be included;
\item Include geometric series and He \& Tang's method \cite{he2008} fitting method;
\item Check if fitting problems for Pareto distribution can occur (see pareto help page in VGAM: \url{http://finzi.psych.upenn.edu/R/library/VGAM/html/pareto1.html} and also references in McGuill's chapter on sads in \cite{magurran2011}.
\end{itemize}

\section{Diagnostic}
\label{sec:graphical-functions}
\begin{itemize}
\item \textbf{DONE} Include (...) arguments in function \code{qqsad}.
\item Check if all functions for diagnostic plots have the (...) argument.
\item For \code{qqsad} consider to use the function qqline to draw the line 
  (seems to allow any probability distribution thorugh argiment \code{probs}).
  If not posible, at least add argument \code{probs} to control the line slope.
\end{itemize}
\section{Other functions}
\label{sec:other-functions}
\begin{itemize}
\item Include Connoly's et al. \cite{connoly2009} bootstrap method in \code{rsad}
\item Include functions for sars, starting with those proposed by Coleman \cite{coleman1981} and Kobayashi \cite{kobayashi1980}.
\end{itemize}

\section{Help pages}
\label{sec:help-pages}
\begin{itemize}
\item Include links to the functions cited in the \code{seealso} section
\item Use markups for codes, url, etc
\item For quantile functions that use search algorithm or approxfun include this information in the note section of help page.
\item Add Paulo's email in all help pages
\item Add keywords 
\end{itemize}

\bibliographystyle{plain}
\bibliography{vignetes}
\end{document}
