\documentclass[11pt, A4]{article}
\usepackage[brazil]{babel}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}
\usepackage{Sweave}
%\usepackage{natbib}
\setlength{\parindent}{0pt}
\setlength{\hoffset}{-0.5in}
\setlength{\textwidth}{6in}
\setlength{\voffset}{-0.1in}
%\pdfpagewidth=\paperwidth
%\pdfpageheight=\paperheight
\newcommand{\R}{{\sf R}}
\newcommand{\code}[1]{\texttt{#1}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

%\setkeys{Gin}{width=0.9\textwidth}
\title{Package sads: ToDo list}
\author{Paulo Inácio Prado}
\maketitle

\section{Bugs and Issues}
\label{sec:bugs-issues}
\begin{itemize}
\item Check why
  @ 
<<eavl=T>>=
pzipf(10,N=100,s=2) - sum(dzipf(1:10,N=100,s=2))
@ %def 
gives a small difference. Once solved include this command in help page. 
\item Check why
  @ 
<<>>=
p.123 <-ppareto(1:3,shape=3,scale=1) 
sum(qpareto(p.123, shape=3, scale=1)-1:3)
@ %def 
gives a small difference. Once solved include this command in help page. 
  
\end{itemize}

\section{Distributions}
\label{sec:distributions}
\begin{itemize}
\item Continuous power
\item Truncated power (or Power-bend)
\item Geometric series
\item Broken-stick (= Poisson sample of exponential?)
\item Make invalid parameters return \code{NaN}, instead than stoping!
\item Allow Pareto distribution to return zero values when scale >= min(x). (Maybe not a good idea: may cause fitting problems.). 
\end{itemize}

\section{Fitting}
\label{sec:fiting-functions}
\begin{itemize}
\item Evaluate if Mouillot \& Lepretre's \cite{mouillot2000} method for fitting Zipf-Mandelbrot is useful to find starting values for \code{fitmand};
\item Evaluate if Wilson's \cite{wilson2009} methods for fitting rads can/should be included;
\item Include geometric series and He \& Tang's method \cite{he2008} fitting method;
\item Check if fitting problems for Pareto distribution can occur (see pareto help page in VGAM: \url{http://finzi.psych.upenn.edu/R/library/VGAM/html/pareto1.html} and also references in McGuill's chapter on sads in \cite{magurran2011}.
\end{itemize}

\section{Diagnostic}
\label{sec:graphical-functions}

\section{Other functions}
\label{sec:other-functions}
\begin{itemize}
\item Include Connoly's et al. \cite{connoly2009} bootstrap method in \code{rsad}
\end{itemize}

\section{Help pages}
\label{sec:help-pages}
\begin{itemize}
\item Include links to the functions cited in the \code{seealso} section
\item Use markups for codes, url, etc
\end{itemize}

\bibliographystyle{plain}
\bibliography{vignetes}
\end{document}
